apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: balancer

resources:
  - ../../base

images:
  - name: ghcr.io/codeforphilly/balancer-main/app
    newTag: 1.1.5

configMapGenerator:
  - name: balancer-config
    behavior: merge
    literals:
      - HOSTNAME=balancerproject.org
    envs:
      - balancer.env

labels:
  - includeSelectors: true
    pairs:
      environment: production
      app.kubernetes.io/instance: balancer-production

patches:
  - target:
      kind: ListenerSet
      name: balancer-listeners
    patch: |
      - op: replace
        path: /spec/listeners/0/hostname
        value: balancerproject.org
      - op: replace
        path: /spec/listeners/1/hostname
        value: balancerproject.org
  - target:
      kind: HTTPRoute
      name: balancer
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: balancerproject.org
  - target:
      kind: HTTPRoute
      name: balancer-http-redirect
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: balancerproject.org