# This dockerfile builds an image for a Vite development server
# Use the official Node.js image as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Build the project
# RUN npm run build

# Expose a port if required
# EXPOSE 3000

# Start the dev server
CMD [ "npm", "run", "dev" ]

# Set the image name
ARG IMAGE_NAME
ENV IMAGE_NAME $IMAGE_NAME