apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: balancer-db
  namespace: balancer
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: balancer
      owner: balancer
      secret:
        name: balancer-db-credentials
  postgresql:
    parameters:
      shared_preload_libraries: 'vector'
