apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - database.yaml

patches:
  - target:
      kind: Database
      name: balancer
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: cloudnative-pg
