# Generated by Django 4.2.3 on 2024-03-17 21:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('manic', 'Manic'), ('hypomanic', 'Hypomanic'), ('depressed', 'Depressed'), ('euthymic', 'Euthymic')], max_length=10)),
                ('first', models.CharField(choices=[('manic-first', 'Risperidone, Olanzapine'), ('manic-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate, Ziprasidone'), ('manic-third', 'Haloperidol'), ('hypomanic-first', 'Risperidone, Olanzapine'), ('hypomanic-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate'), ('hypomanic-third', 'Haloperidol, Ziprasidone'), ('depressed-first', 'Quetiapine, Lurasidone'), ('depressed-second', 'Olanzapine plus Fluoxetine, Valproate (divalproex), Quetiapine plus Lithium, Quetiapine plus Valproate, Lurasidone plus Lithium, Lurasidone plus Valproate, Lithium plus Valproate, Lithium plus Lamotrigine'), ('depressed-third', 'Lamotrigine, Lithium, Olanzapine, Carbamazepine, Cariprazine, Olanzapine plus lithium, Olanzapine plus valproate'), ('euthymic-first', 'Quetiapine'), ('euthymic-second', 'Lamotrigine, Lithium, Olanzapine plus Fluoxetine'), ('euthymic-third', 'Lurasidone, Citalopram, Escitalopram, Sertraline')], max_length=100)),
                ('second', models.CharField(choices=[('manic-first', 'Risperidone, Olanzapine'), ('manic-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate, Ziprasidone'), ('manic-third', 'Haloperidol'), ('hypomanic-first', 'Risperidone, Olanzapine'), ('hypomanic-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate'), ('hypomanic-third', 'Haloperidol, Ziprasidone'), ('depressed-first', 'Quetiapine, Lurasidone'), ('depressed-second', 'Olanzapine plus Fluoxetine, Valproate (divalproex), Quetiapine plus Lithium, Quetiapine plus Valproate, Lurasidone plus Lithium, Lurasidone plus Valproate, Lithium plus Valproate, Lithium plus Lamotrigine'), ('depressed-third', 'Lamotrigine, Lithium, Olanzapine, Carbamazepine, Cariprazine, Olanzapine plus lithium, Olanzapine plus valproate'), ('euthymic-first', 'Quetiapine'), ('euthymic-second', 'Lamotrigine, Lithium, Olanzapine plus Fluoxetine'), ('euthymic-third', 'Lurasidone, Citalopram, Escitalopram, Sertraline')], max_length=100)),
                ('third', models.CharField(choices=[('manic-first', 'Risperidone, Olanzapine'), ('manic-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate, Ziprasidone'), ('manic-third', 'Haloperidol'), ('hypomanic-first', 'Risperidone, Olanzapine'), ('hypomanic-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate'), ('hypomanic-third', 'Haloperidol, Ziprasidone'), ('depressed-first', 'Quetiapine, Lurasidone'), ('depressed-second', 'Olanzapine plus Fluoxetine, Valproate (divalproex), Quetiapine plus Lithium, Quetiapine plus Valproate, Lurasidone plus Lithium, Lurasidone plus Valproate, Lithium plus Valproate, Lithium plus Lamotrigine'), ('depressed-third', 'Lamotrigine, Lithium, Olanzapine, Carbamazepine, Cariprazine, Olanzapine plus lithium, Olanzapine plus valproate'), ('euthymic-first', 'Quetiapine'), ('euthymic-second', 'Lamotrigine, Lithium, Olanzapine plus Fluoxetine'), ('euthymic-third', 'Lurasidone, Citalopram, Escitalopram, Sertraline')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.BinaryField()),
                ('date_of_upload', models.DateTimeField(auto_now_add=True)),
                ('size', models.BigIntegerField()),
                ('page_count', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.CharField(blank=True, max_length=255, null=True)),
                ('analyzed', models.DateTimeField(blank=True, null=True)),
                ('approved', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
