# Generated by Django 4.2.3 on 2023-12-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('manic', 'Manic'), ('hypomanic', 'Hypomanic'), ('depressed', 'Depressed'), ('euthymic', 'Euthymic')], max_length=10)),
                ('first', models.CharField(choices=[('mania-first', 'Risperidone, Olanzapine'), ('mania-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate, Ziprasidone'), ('mania-third', 'Haloperidol'), ('hypomania-first', 'Risperidone, Olanzapine'), ('hypomania-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate'), ('hypomania-third', 'Haloperidol, Ziprasidone'), ('depression-first', 'Quetiapine, Lurasidone'), ('depression-second', 'Olanzapine plus Fluoxetine, Valproate (divalproex), Quetiapine plus Lithium, Quetiapine plus Valproate, Lurasidone plus Lithium, Lurasidone plus Valproate, Lithium plus Valproate, Lithium plus Lamotrigine'), ('depression-third', 'Lamotrigine, Lithium, Olanzapine, Carbamazepine, Cariprazine, Olanzapine plus lithium, Olanzapine plus valproate'), ('euthymic-first', 'Quetiapine'), ('euthymic-second', 'Lamotrigine, Lithium, Olanzapine plus Fluoxetine'), ('euthymic-third', 'Lurasidone, Citalopram, Escitalopram, Sertraline')], max_length=100)),
                ('second', models.CharField(choices=[('mania-first', 'Risperidone, Olanzapine'), ('mania-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate, Ziprasidone'), ('mania-third', 'Haloperidol'), ('hypomania-first', 'Risperidone, Olanzapine'), ('hypomania-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate'), ('hypomania-third', 'Haloperidol, Ziprasidone'), ('depression-first', 'Quetiapine, Lurasidone'), ('depression-second', 'Olanzapine plus Fluoxetine, Valproate (divalproex), Quetiapine plus Lithium, Quetiapine plus Valproate, Lurasidone plus Lithium, Lurasidone plus Valproate, Lithium plus Valproate, Lithium plus Lamotrigine'), ('depression-third', 'Lamotrigine, Lithium, Olanzapine, Carbamazepine, Cariprazine, Olanzapine plus lithium, Olanzapine plus valproate'), ('euthymic-first', 'Quetiapine'), ('euthymic-second', 'Lamotrigine, Lithium, Olanzapine plus Fluoxetine'), ('euthymic-third', 'Lurasidone, Citalopram, Escitalopram, Sertraline')], max_length=100)),
                ('third', models.CharField(choices=[('mania-first', 'Risperidone, Olanzapine'), ('mania-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate, Ziprasidone'), ('mania-third', 'Haloperidol'), ('hypomania-first', 'Risperidone, Olanzapine'), ('hypomania-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate'), ('hypomania-third', 'Haloperidol, Ziprasidone'), ('depression-first', 'Quetiapine, Lurasidone'), ('depression-second', 'Olanzapine plus Fluoxetine, Valproate (divalproex), Quetiapine plus Lithium, Quetiapine plus Valproate, Lurasidone plus Lithium, Lurasidone plus Valproate, Lithium plus Valproate, Lithium plus Lamotrigine'), ('depression-third', 'Lamotrigine, Lithium, Olanzapine, Carbamazepine, Cariprazine, Olanzapine plus lithium, Olanzapine plus valproate'), ('euthymic-first', 'Quetiapine'), ('euthymic-second', 'Lamotrigine, Lithium, Olanzapine plus Fluoxetine'), ('euthymic-third', 'Lurasidone, Citalopram, Escitalopram, Sertraline')], max_length=100)),
            ],
        ),
    ]
