# Generated by Django 4.2.3 on 2024-04-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='analyzed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='date_of_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='source_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
