# Generated by Django 4.2.3 on 2024-05-28 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uploadfile_analyzed_uploadfile_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='date_of_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='page_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AI_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('SettingsLabel', models.CharField(max_length=255, null=True)),
                ('SettingValue', models.TextField()),
                ('SourceTable', models.TextField()),
                ('SourceTableGUID', models.CharField(max_length=255, null=True, unique=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('ModifiedByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AI_settings',
            },
        ),
        migrations.CreateModel(
            name='AI_PromptStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('PromptText', models.TextField()),
                ('IsActive', models.BooleanField(default=True)),
                ('Area', models.CharField(choices=[('system', 'System Prompt'), ('dashboard', 'Dashboard'), ('settings', 'Settings Page')], default='dashboard', max_length=100)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts_created', to=settings.AUTH_USER_MODEL)),
                ('ModifiedByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AI_PromptStorage',
            },
        ),
    ]
