# Generated by Django 4.2.3 on 2023-12-13 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_populate_state_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='statemedication',
            name='first',
            field=models.CharField(choices=[('manic-first', 'Risperidone, Olanzapine'), ('manic-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate, Ziprasidone'), ('manic-third', 'Haloperidol'), ('hypomanic-first', 'Risperidone, Olanzapine'), ('hypomanic-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate'), ('hypomanic-third', 'Haloperidol, Ziprasidone'), ('depressed-first', 'Quetiapine, Lurasidone'), ('depressed-second', 'Olanzapine plus Fluoxetine, Valproate (divalproex), Quetiapine plus Lithium, Quetiapine plus Valproate, Lurasidone plus Lithium, Lurasidone plus Valproate, Lithium plus Valproate, Lithium plus Lamotrigine'), ('depressed-third', 'Lamotrigine, Lithium, Olanzapine, Carbamazepine, Cariprazine, Olanzapine plus lithium, Olanzapine plus valproate'), ('euthymic-first', 'Quetiapine'), ('euthymic-second', 'Lamotrigine, Lithium, Olanzapine plus Fluoxetine'), ('euthymic-third', 'Lurasidone, Citalopram, Escitalopram, Sertraline')], max_length=100),
        ),
        migrations.AlterField(
            model_name='statemedication',
            name='second',
            field=models.CharField(choices=[('manic-first', 'Risperidone, Olanzapine'), ('manic-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate, Ziprasidone'), ('manic-third', 'Haloperidol'), ('hypomanic-first', 'Risperidone, Olanzapine'), ('hypomanic-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate'), ('hypomanic-third', 'Haloperidol, Ziprasidone'), ('depressed-first', 'Quetiapine, Lurasidone'), ('depressed-second', 'Olanzapine plus Fluoxetine, Valproate (divalproex), Quetiapine plus Lithium, Quetiapine plus Valproate, Lurasidone plus Lithium, Lurasidone plus Valproate, Lithium plus Valproate, Lithium plus Lamotrigine'), ('depressed-third', 'Lamotrigine, Lithium, Olanzapine, Carbamazepine, Cariprazine, Olanzapine plus lithium, Olanzapine plus valproate'), ('euthymic-first', 'Quetiapine'), ('euthymic-second', 'Lamotrigine, Lithium, Olanzapine plus Fluoxetine'), ('euthymic-third', 'Lurasidone, Citalopram, Escitalopram, Sertraline')], max_length=100),
        ),
        migrations.AlterField(
            model_name='statemedication',
            name='third',
            field=models.CharField(choices=[('manic-first', 'Risperidone, Olanzapine'), ('manic-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate, Ziprasidone'), ('manic-third', 'Haloperidol'), ('hypomanic-first', 'Risperidone, Olanzapine'), ('hypomanic-second', 'Aripiprazole, Asenapine, Carbamazepine, Cariprazine, Lithium, Paliperidone, Quetiapine, Valproate'), ('hypomanic-third', 'Haloperidol, Ziprasidone'), ('depressed-first', 'Quetiapine, Lurasidone'), ('depressed-second', 'Olanzapine plus Fluoxetine, Valproate (divalproex), Quetiapine plus Lithium, Quetiapine plus Valproate, Lurasidone plus Lithium, Lurasidone plus Valproate, Lithium plus Valproate, Lithium plus Lamotrigine'), ('depressed-third', 'Lamotrigine, Lithium, Olanzapine, Carbamazepine, Cariprazine, Olanzapine plus lithium, Olanzapine plus valproate'), ('euthymic-first', 'Quetiapine'), ('euthymic-second', 'Lamotrigine, Lithium, Olanzapine plus Fluoxetine'), ('euthymic-third', 'Lurasidone, Citalopram, Escitalopram, Sertraline')], max_length=100),
        ),
    ]
