# Generated by Django 4.2.3 on 2024-03-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ai_settings_ai_promptstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_settings',
            name='settingsLabel',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
