# Generated by Django 4.2.3 on 2024-07-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_uploadfile_date_of_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbacktype', models.CharField(max_length=100)),
            ],
        ),
    ]
