# Generated by Django 4.2.3 on 2024-03-23 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ai_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_PromptStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('PromptText', models.TextField()),
                ('IsActive', models.BooleanField(default=True)),
                ('Area', models.CharField(choices=[('systemPrompt', 'System Prompt'), ('dashboard', 'Dashboard'), ('settings', 'Settings Page')], default='dashboard', max_length=100)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts_created', to=settings.AUTH_USER_MODEL)),
                ('ModifiedByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
