# Generated by Django 4.2.3 on 2024-07-30 10:21

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.vector
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_uploadfile_uploaded_by_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('page_num', models.IntegerField(default=1)),
                ('chunk_number', models.IntegerField()),
                ('embedding_sentence_transformers', pgvector.django.vector.VectorField(dimensions=384, null=True)),
                ('date_of_upload', models.DateTimeField(auto_now_add=True)),
                ('upload_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='api.uploadfile')),
            ],
        ),
    ]
