# Generated by Django 4.2.3 on 2024-07-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='feedback',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedbacktype',
            field=models.CharField(choices=[('issue', 'Issue'), ('new_feature', 'New Feature'), ('general', 'General')], default='general', max_length=100),
        ),
    ]
