# Generated by Django 4.2.3 on 2025-02-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_medrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medrule',
            name='medication',
        ),
        migrations.AddField(
            model_name='medrule',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medrule',
            name='medications',
            field=models.ManyToManyField(related_name='med_rules', to='api.medication'),
        ),
        migrations.AddField(
            model_name='medrule',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='med_rules', to='api.embeddings'),
        ),
        migrations.AlterModelTable(
            name='medrule',
            table='api_medrule',
        ),
    ]
