# Generated by Django 4.2.3 on 2025-02-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_medrule_medication_medrule_explanation_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medrule',
            unique_together={('rule_type', 'history_type')},
        ),
    ]
