# Generated by Django 4.2.3 on 2025-07-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_medrule_medications_medrulesource_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='medrule',
                    name='medications',
                    field=models.ManyToManyField(
                        related_name='med_rules',
                        to='api.medication',
                    ),
                ),
            ]
        ),
    ]
