# Generated by Django 4.2.3 on 2025-10-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_medrule_medications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medrule',
            name='rule_type',
            field=models.CharField(choices=[('INCLUDE', 'Include'), ('EXCLUDE', 'Exclude')], max_length=500),
        ),
    ]
