# Generated by Django 4.2.3 on 2025-11-26 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_medrule_rule_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticSearchUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('query_text', models.TextField(blank=True, help_text='The search query text', null=True)),
                ('document_name', models.TextField(blank=True, help_text='Document name filter if used', null=True)),
                ('document_guid', models.UUIDField(blank=True, help_text='Document GUID filter if used', null=True)),
                ('num_results_requested', models.IntegerField(default=10, help_text='Number of results requested')),
                ('encoding_time', models.FloatField(help_text='Time to encode query in seconds')),
                ('db_query_time', models.FloatField(help_text='Time for database query in seconds')),
                ('num_results_returned', models.IntegerField(help_text='Number of results returned')),
                ('min_distance', models.FloatField(blank=True, help_text='Minimum L2 distance (null if no results)', null=True)),
                ('max_distance', models.FloatField(blank=True, help_text='Maximum L2 distance (null if no results)', null=True)),
                ('median_distance', models.FloatField(blank=True, help_text='Median L2 distance (null if no results)', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the search (null for unauthenticated users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semantic_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='api_semanti_timesta_0b5730_idx'), models.Index(fields=['user', '-timestamp'], name='api_semanti_user_id_e11ecb_idx')],
            },
        ),
    ]
