# Default values for Balancer-main

backend:
# Gunicorn/Django container variables
  existingSecret: backend
  image:
    repository: "ghcr.io/codeforphilly/balancer-main/backend"
    tag: "latest"
  env:
    DATABASE: "postgres"
    DEBUG: "FALSE"
    DJANGO_ALLOWED_HOSTS: "frontend localhost 127.0.0.1 [::1]"
    SQL_ENGINE: "django.db.backends.postgresql"
    LOGIN_REDIRECT_URL: "https://balancertestsite.com/login"
    EMAIL_HOST: "smtp.gmail.com"
    EMAIL_PORT: "587"
    EMAIL_HOST_USER: "balancer-noreply@gmail.com"

frontend:
#  Nginx/frontend container variables
  image:
    repository: "ghcr.io/codeforphilly/balancer-main/frontend"
    tag: "latest"
  server_name: "localhost"

postgresql:
#  postgres database container variables
  existingSecret: postgresql
  image:
    repository: "postgres"
    tag: "15"
  port: "5432"

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
