apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: balancer

resources:
  - ../../base
  - configmap.yaml

patches:
  - target:
      kind: Deployment
      name: balancer
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          configMapRef:
            name: balancer-db-config
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: balancer-db-credentials
                key: password
