apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: balancer

resources:
  - ../../base

images:
  - name: ghcr.io/codeforphilly/balancer-main/app
    newTag: latest

patches:
  - target:
      kind: ListenerSet
      name: balancer-listeners
    patch: |-
      - op: replace
        path: /spec/listeners/0/hostname
        value: sandbox.balancerproject.org
      - op: replace
        path: /spec/listeners/1/hostname
        value: sandbox.balancerproject.org
  - target:
      kind: HTTPRoute
      name: balancer
    patch: |-
      - op: add
        path: /spec/hostnames
        value: ["sandbox.balancerproject.org"]
  - target:
      kind: HTTPRoute
      name: balancer-redirect
    patch: |-
      - op: add
        path: /spec/hostnames
        value: ["sandbox.balancerproject.org"]
