# Generated by Django 4.2.3 on 2024-03-20 21:38

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_create_pgvector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embeddings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=3)),
            ],
        ),
    ]
