# Generated by Django 4.2.3 on 2024-03-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddings',
            name='chunk_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
