# Generated by Django 4.2.3 on 2024-03-21 01:17

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_embeddings_chunk_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddings',
            name='embedding',
            field=pgvector.django.VectorField(dimensions=384),
        ),
    ]
