# This image runs the Django lightweight development web server without the frontend.
# Intended to be run along with the frontend dev server.
# pull official base image
FROM python:3.11.4-slim-buster

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy project
COPY . .

# Correct line endings in entrypoint.sh and make it executable
RUN sed -i 's/\r$//' entrypoint.sh && chmod +x entrypoint.sh

# run entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]

# Default command to run on container start
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000", "--noreload"]
