apiVersion: v1
data:
  {{- toYaml .Values.backend.env | nindent 2 }}
  SQL_PORT: "{{ .Values.postgresql.port }}"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: backend-env
