apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: backend
spec:
  ports:
    - name: "gunicorn"
      port: 8000
      targetPort: 8000
  selector:
    app.kubernetes.io/component: backend
