apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app.kubernetes.io/component: db
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.port }}
  type: NodePort
  