apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.prod.yml -o helm-chart
    kompose.version: 1.31.2 (a92241f79)
  labels:
    app.kubernetes.io/component: frontend
  name: frontend
spec:
  ports:
    - name: "http"
      port: 80
  selector:
    app.kubernetes.io/component: frontend
